## EXCPT-1

In [22]:
n=int(input("Enter the number of digits:"))
if n>0:
    number=int(input(f"Enter  a {n}-digit integer:"))
    if number>=10**(n-1) and number <10**n:
        for i in range(n):
            digit=number//(10**(n-1))
            print(digit)
            number%=10**(n-1)
            n-=1
    else:
        print(f"Please enter a {n}-digit integer.")
else: 
    print("Please enter a valid number of digit(greater then 0).")

Enter the number of digits:4
Enter  a 4-digit integer:5678
5
6
7
8


## EXCPT-2

In [24]:
a=int(input("Enter the first number:"))
b=int(input("Enter the second number:"))
c=int(input("Enter the third number: "))
d=int(input("Enter the fourth number:"))
if a>b:a,b=b,a
if c>d:c,d=d,c
if a>c:a,c=c,a
if b>d:b,d=d,b
if b>c:b,c=c,b
print("The sorted numbers are:",a,b,c,d)

Enter the first number:10
Enter the second number:5
Enter the third number: 7
Enter the fourth number:3
The sorted numbers are: 3 5 7 10


In [25]:
a=int(input("Enter the first number:"))
b=int(input("Enter the second number:"))
c=int(input("Enter the third number: "))
d=int(input("Enter the fourth number:"))
if a>b:a,b=b,a
if c>d:c,d=d,c
if a>c:a,c=c,a
if b>d:b,d=d,b
if b>c:b,c=c,b
print("The sorted numbers are:",d,c,b,a)

Enter the first number:10
Enter the second number:5
Enter the third number: 7
Enter the fourth number:3
The sorted numbers are: 10 7 5 3


## EXCPT-3

In [3]:
number=int(input("Enter an n-digit number:"))
original_number=number
reversed_number=0
while number>0:
    digit=number%10
    reversed_number=reversed_number*10+digit
    number//=10
if original_number==reversed_number:
    print("Palindrome")
else:
    print("Not a Palindrome")

Enter an n-digit number:1234
Not a Palindrome


## EXCPT-4

In [11]:
n=int(input("Enter an integer for the multiplication table:"))
print(f"Multiplication Table for {n}:")
for i in range(1,11):
    result=n*i
    print(f"{n}*{i}={result}")

Enter an integer for the multiplication table:5
Multiplication Table for 5:
5*1=5
5*2=10
5*3=15
5*4=20
5*5=25
5*6=30
5*7=35
5*8=40
5*9=45
5*10=50


## EXCPT-5

In [28]:
n=int(input("Enter the number of elements:"))
numbers=[int(input(f"Enter number {i+1}:"))for i in range(n)]
mean=sum(numbers)/n
numbers.sort()
if n%2==0:
    median=(numbers[n//2-1]+numbers[n//2])/2
else:
    median=numbers[n//2]
frequency={num:numbers.count(num) for num in numbers}
max_count=max(frequency.values())
mode=[k for k,v in frequency.items() if v==max_count]
if len(mode)==n:
    mode="No mode"
mean_difference_squared_sum=sum((x-mean)**2 for x in numbers)
varience_sample=mean_difference_squared_sum/(n-1) if n>1 else 0
varience_population=mean_difference_squared_sum/n
std_deviation_sample=varience_sample**0.5
std_deviation_population=varience_population**0.5
print(f"mean:{mean}")
print(f"median:{median}")
print(f"mode:{mode}")
print(f"Sample Varience:{varience_sample}") 
print(f"Population varience:{varience_population}")
print(f"sample Standard Deviation:{std_deviation_sample}")
print(f"Population standard Deviation:{std_deviation_population}")

Enter the number of elements:6
Enter number 1:4
Enter number 2:8
Enter number 3:6
Enter number 4:5
Enter number 5:3
Enter number 6:9
mean:5.833333333333333
median:5.5
mode:No mode
Sample Varience:5.366666666666667
Population varience:4.472222222222222
sample Standard Deviation:2.316606713852541
Population standard Deviation:2.1147629234082532


## EXCPT-6

In [1]:
number=int(input("Enter the integer number:"))
revs_number=0
while(number>0):
    remainder=number%10
    revs_number=(revs_number*10)+remainder
    number=number//10
print("The reverse number is:{}".format(revs_number))

Enter the integer number:253
The reverse number is:352


## EXCPT-7

In [14]:
def interchange_digits(number,pos1,pos2):
    number_str=str(number)
    number_list=list(number_str)
    number_list[pos1-1],number_list[pos2-1]=number_list[pos2-1],number_list[pos1-1]
    interchanged_number=int("".join(number_list))
    return interchanged_number
number=int(input('Enter the user input:'))
pos1=int(input('Enter th 1st position which u want to swap:'))
pos2=int(input('Enter th 2st position which u want to swap:'))
interchanged_number=interchange_digits(number,pos1,pos2)
print("original number:",number)
print("Interchanged number:",interchanged_number)

Enter the user input:12345
Enter th 1st position which u want to swap:2
Enter th 2st position which u want to swap:3
original number: 12345
Interchanged number: 13245


## EXCPT-8

In [3]:
def capitalize_strings(string_list):
    return[s.capitalize()for s in string_list]
input_strings=['hello','good','how','simple']
capitalize_strings=capitalize_strings(input_strings)
print(capitalize_strings)

['Hello', 'Good', 'How', 'Simple']


## EXCPT-9

In [19]:
def count_duplicate_words(sentence):
    words=sentence.split()
    word_count={}
    for word in words:
        word=word.lower()
        if word in word_count:
            word_count[word]+=1
        else:
            word_count[word]=1
            
    duplicates={word:count for word,count in word_count.items() if count>1}
    if duplicates:
        print("Duplicates words and their counts:")
        for word,count in duplicates.items():
            print(f"{word}:{count}")
    else:
        print("No duplicate words found")
sentence=input("Enter a sentence:")
count_duplicate_words(sentence)

Enter a sentnce:hello welcome to lab
No duplicate words found


## EXCPT-10

In [2]:
from numpy import asarray
data=[[1,2,3],[4,5,6]]
data=asarray(data)
print("Numpy Array")
print(data)
print("________________")
totalr=data.sum(axis=1)
totalc=data.sum(axis=0)
print("row sum")
print(totalr)
print("Column sum")
print(totalc)
print("________________")
meanr=data.mean(axis=1)
meanc=data.mean(axis=0)
print("row Mean")
print(meanr)
print("Column Mean")
print(meanc)
print("________________")
stdr=data.std(axis=1)
stdc=data.std(axis=0)
print("row STD")
print(stdr)
print("Column STD")
print(stdc)

Numpy Array
[[1 2 3]
 [4 5 6]]
________________
row sum
[ 6 15]
Column sum
[5 7 9]
________________
row Mean
[2. 5.]
Column Mean
[2.5 3.5 4.5]
________________
row STD
[0.81649658 0.81649658]
Column STD
[1.5 1.5 1.5]


## EXCPT-11

In [6]:
import csv
file =open('sample.csv',mode='r')
csv_reader=csv.reader(file,delimiter=',')
line_count=0
for row in csv_reader:
    if line_count==0:
        
        print(f'Column names are {", ".join(row)}')
        line_count+=1
    else:
        print(f'\t{row[0]} works in the {row[1]} department,and was born in {row[2]}.')
        line_count+=1
print(f'Processed {line_count} lines.')
file.close()

Column names are name, department, birthday_month
	John Smith works in the Accounting department,and was born in november.
	Erica Meyers works in the IT department,and was born in march.
	Rocky works in the HR department,and was born in april.
Processed 4 lines.


## EXCPT-12

In [13]:
import pandas as pd
def read_html_to_dict(html_file):
    tables=pd.read_html(html_file)
    tables_dict={}
    for i,table in enumerate(tables):
        table_dict=table.to_dict(orient='list')
        tables_dict[f'Table_{i+1}']=table_dict
    return tables_dict
if __name__=='__main__':
    html_file='sample.html'
    result=read_html_to_dict(html_file)
    print(result)

{'Table_1': {'Name': ['Alice', 'Bob'], 'Age': [24, 27]}, 'Table_2': {'Country': ['France', 'Italy'], 'Capital': ['Paris', 'Rome']}}
